import { NextResponse } from "next/server";

// This file intentionally contains a minimal non-JSX handler to avoid duplicate JSX parsing
// The real OG image is generated by `route.tsx` (TSX). This route proxies by returning 307 to the TSX
export async function GET(req: Request) {
  const url = new URL(req.url);
  // extract id from pathname (last segment)
  const parts = url.pathname.split("/").filter(Boolean);
  const id = parts[parts.length - 1] ?? "";
  const target = new URL(`/api/og/report/${encodeURIComponent(id)}`, url.origin);
  for (const [k, v] of url.searchParams.entries()) target.searchParams.append(k, v);
  return NextResponse.redirect(target.toString(), 307);
}
