name: Alerts

on:
  schedule:
    - cron: "0 2 * * *" # daily at 02:00 UTC
  workflow_dispatch: {}

jobs:
  alerts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install
        run: pnpm install
      - name: Run prisma migrate (deploy)
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: pnpm --dir . prisma migrate deploy
      - name: Run alerts script
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
        run: pnpm --dir . ts-node ./scripts/alerts.ts
