name: Price Watcher

on:
  schedule:
    - cron: "0 2 * * *" # daily at 02:00 UTC
  workflow_dispatch: {}

jobs:
  run-watcher:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Run price watcher
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: pnpm --dir ./ ts-node ./scripts/price-watcher.ts
